### ISSUE TITLE
Exercise builder page

### ISSUE THREAD

**Issue by chrispho** [chrispho/language-study-app#50]
**Details:** User-friendly interface that allows users to create and customize the various exercise types without needing to submit raw JSON files. 
**Purpose:** Allow users to create their own exercises that tailor to individual language learning needs. Users that have different preferences in question content can add their own questions and answers for any of the supported formats.
**Expected outcomes:** Exercise builder page that supports multiple choice, fill-in-the-blank, matching, and listening comprehension. Created exercises will be stored per user in an exercise library.

**Comment by mshivang010** [comment]
The issue is well-scoped, emphasizing a user-friendly interface for exercise customization without technical barriers. The purpose aligns with personalized language learning needs. Ensure the expected outcomes detail robust support for all exercise types and seamless user-specific storage.

**Comment by chrispho** [comment]
This feature is out of scope for this project and will not be completed. Can reopen in the future if functionality is needed.
