### ISSUE TITLE
Implement site wide language translation feature

### ISSUE THREAD

**Issue by rajkive** [chrispho/language-study-app#51]
**Details:** Maintain a translations database. Identify all user-visible strings and convert them into translation keys. Ensure content fetched dynamically (e.g., via APIs) supports translation.
**Purpose:** Enhance the user experience by allowing users to interact with the website in their preferred language.
**Expected outcomes:** Users can navigate and interact with the website in their native language. Broaden the user base by accommodating non-English speakers.

**Comment by chrispho** [comment]
I like this idea of allowing non-English speakers to use our web application. How are the user-visible strings and their translations going to be stored? Is a relational database the right format to be using for a large mass of unsorted data?

Alternatively, could we use an existing tool to flag certain html elements for translation via something like the Google Translate API?
