### ISSUE TITLE
Translation history

### ISSUE THREAD

**Issue by atch2203** [chrispho/language-study-app#58]
Details: Users will see a history of their most recent translations, which will also be stored in the backend.
Purpose: Translation history allows for users to restore old queries that they might want to reuse or change without having to type them in again.
Expected outcomes: An area on the translation page will display information about previous translations.

**Comment by chrispho** [comment]
This is definitely a good feature to include in the translation feature. Users will benefit greatly from translation history to quickly access something that they've translated before.

How much history will be stored? Will this be stored locally or per user?

**Comment by atch2203** [comment]
Since we currently don't have authentication, I will be making this feature global until otherwise. History is stored forever, currently with no way of deletion. I might add that functionality depending on the complexity.
