### ISSUE TITLE
User feedback for translation success/errors

### ISSUE THREAD

**Issue by atch2203** [chrispho/language-study-app#59]
Details: Right now, if an error happens (eg source language and output language is identical), the api will respond with an error that will just be placed into the output box. 
Purpose: Create a clear pop up that indicates when an error happens vs when the translation is successful.
Expected outcomes: Clear, user-friendly feedback whenever a translation is requested.

**Comment by ghost** [comment]
Sounds reasonable to me. I think this issue is well defined and scoped such that it should be easily completable.
