### ISSUE TITLE
Connect translations to creation of flashcards

### ISSUE THREAD

**Issue by atch2203** [chrispho/language-study-app#60]
Details: With the flashcard set structure, the previous method of adding flashcards in the front-end does not work.
Purpose: This feature aims to account for the new structure by allowing users to add flashcards to sets from the translation page without switching contexts.
Expected outcomes: Users should be able to select a set to add a translation to and click a button to add flashcards easily.

**Comment by chrispho** [comment]
Good catch on ensuring that the translation page still works with the flashcards now that there is a new class structure.

Will users have the ability to create a new set in this translation/flashcard UI if they do not want the new flashcard to be part of an existing set?

**Comment by atch2203** [comment]
I do not plan on allowing users to make a new set, as that functionality is decently complex and already exists in the flashcard page.
I will have to look at the new backend code #63, but it shouldn't be too complex.

**Comment by atch2203** [comment]
Right now the flashcard backend is not working, so I removed the translation to flashcard button in #67.

**Comment by atch2203** [comment]
As mentioned earlier, this feature cannot be implemented if the flashcard sets cannot be retrieved.
